config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  
  get 'signup' => 'users#new'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  post "/projects/task/:id" => 'tasks#update'
  
  resources :users
  resources :projects
  resources :tasks, only: [:create, :destroy]

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 250 }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :project_id, presence: true
  validates :name, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {maximum: 150}
  validates :progress_state, presence: true 
  
  enum progress_state: [:planned, :active, :complete]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  
  has_many :projects, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 }
  
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  #Retruns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
    # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  #add access controls
  
  def new 
    @project = current_user.projects.build
  end
  
  def create
    @project = current_user.projects.build(project_params)
    if @project.save
    flash[:success] = "Project created!"
     redirect_to root_url #temp. change to project show for task adding  
    else
      render 'new'
    end
  end
  
  def show
    @project = Project.find(params[:id])
    @task = @project.tasks.build
    @tasks = @project.tasks.all
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:success] = "Project updated"
      redirect_to root_url
    else
      render 'edit'
    end
  end  
  
  def destroy
    Project.find(params[:id]).destroy
    flash[:success] = "project deleted"
    redirect_to root_url
  end
  
  private 
  
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid credentials'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user
    if @user 
      @projects = @user.projects.all
    end
  end

  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def create
    @project = Project.find(params[:task][:project_id])
    @task = @project.tasks.build(task_params)
    if @task.save
      flash[:success] = "Task added to project"
      redirect_to request.referrer
    else
      redirect_to request.referrer
    end
  end
  
  def update
    @task = Task.find(params[:id])
    origin = Integer(@task[:progress_state])
    destination = Integer(params[:destination])
    if  ((origin - destination).abs == 1 && (0..2) === destination)
      if @task.update_attribute(:progress_state, Task.progress_states.key(destination)) 
        respond_to do |format|
          format.html { render @task }
          format.js
        end
      end
    end
  end
  
  def destroy
    Task.find(params[:id]).destroy
    flash[:success] = "Task Deleted"
    redirect_to request.referrer
  end
  
  private
    def task_params
      params.require(:task).permit(:name, :description, :progress_state, :project_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
  end #remove this
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome " + @user.name
      redirect_to root_url
    else
      render 'new' 
    end
  end
  
  def edit
  end
  
  def update
  end
  
  
  
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    # Before filters
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "ProjectApp"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    #checks first for login in session
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  
  #remembers a user in a persistent session
  def remember(user) 
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
    # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
    # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/_flashes.html.erb
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><a href="https://bitbucket.org/bendandi/rails_project_app">Bitbucket</a></li>
      <li><%= link_to "About", about_path %></li>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
         <% if logged_in? %>
          <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flashes' %>  
      <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/projects/_project.html.erb
<div class="panel panel-default col-sm-12">
  <div class="panel-heading row">
    <h3 class="col-sm-8 "><%= link_to project.name, project_path(project.id) %></h3>
        <% if current_user?(project.user) %>
        <h4 class="col-sm-4">
          <span><%= link_to "", project, method: :delete,
                                   data: { confirm: "You sure?" },
                                   class: "glyphicon glyphicon-trash pull-right"%></span>
          <span><%= link_to "", edit_project_path(project.id), class: "glyphicon glyphicon-pencil pull-right" %></span>
  </h4>
                                   
    <% end %>
  </div>
  <div class="panel-body">
    <%= project.description %>

  </div>
</div>

app/views/projects/_project_list.html.erb
<h1>Your Projects <small><%= link_to " add a project", new_project_path, class: "primary" %></small></h1>

<div class="row" >
<div class="projects col-sm-offset-2 col-sm-8">
  <%= render @projects %>
</div>
</div>

app/views/projects/edit.html.erb
<% provide(:title, 'Update Project') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@project) do |f| %>
      <%= render 'shared/error_messages' , object: f.object%>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>
<h1>New Project</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@project) do |f| %>
      <%= render 'shared/error_messages' , object: f.object%>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.submit "Create project", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<% provide(:title, @project.name) %>


  <h1><%= @project.name%></h1>

  <p class="text-center"><%= @project.description %></p>




<% if @project.tasks.any? %>
<div class="row ">

  <div class="col-sm-4">
    <div class="panel panel-default" >
      <div class="panel-heading">
        <h4 class="panel-title">Planned</h4>
      </div>
      <div class="panel-body" id="0" ondrop="drop_handler(event, this);" 
                                    ondragover="dragover_handler(event)";
                                    ondragenter="dragenter_handler(event, this)",
                                    ondragleave="dragleave_handler(event, this)">
        <%= render @tasks.planned %>
      </div>
    </div> 
  </div>
  
  <div class="col-sm-4">
    <div class="panel panel-default" >
      <div class="panel-heading">
        <h4 class="panel-title">Active</h4>
      </div>
      <div class="panel-body" id="1" ondrop="drop_handler(event, this);" 
                                    ondragover="dragover_handler(event)";
                                    ondragenter="dragenter_handler(event, this)",
                                    ondragleave="dragleave_handler(event, this)">
        <%= render @tasks.active %>
      </div>
    </div> 
  </div>
  
  <div class="col-sm-4" >
    <div class="panel panel-default" >
      <div class="panel-heading">
        <h4 class="panel-title">Complete</h4>
      </div>
      <div class="panel-body" id="2" ondrop="drop_handler(event, this);" 
                                    ondragover="dragover_handler(event);"
                                    ondragenter="dragenter_handler(event, this)",
                                    ondragleave="dragleave_handler(event, this)">
        <%= render @tasks.complete %>
      </div>
    </div> 
  </div>
</div>

<% else %>
  <span>Empty project. Add some tasks</span>
<% end %>


<div class="row">
  <div class="col-sm-4">
  <%= form_for(@task) do |f| %>
    <%= render 'shared/error_messages' , object: f.object%>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
    
    <%= f.hidden_field :project_id, :value => @project.id %>

    <%= f.submit "Add task", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

<script type="text/javascript">
  var origin;
  var taskId; 
  var token = "";
  
  var metaTags=document.getElementsByTagName("meta");
  
  for (var i = 0; i < metaTags.length; i++) {
    if (metaTags[i].getAttribute("name") == "csrf-token") {
        token = metaTags[i].getAttribute("content");
        break;
    }
  };
  
  function dragstart_handler(ev, original_state, task) {
    origin = original_state;
    taskId = task;

    ev.dataTransfer.setData("text/plain", ev.target.id);
  };
  
  function drop_handler(ev, el) {
    ev.preventDefault();
    //only allow dragging one step at a time
    if(Math.abs(origin - el.id) === 1) {
      var data = ev.dataTransfer.getData("text");
      el.appendChild(document.getElementById(data));
      updateTaskProgressState(taskId , el.id);
      el.parentElement.classList.toggle('panel-success');    
    }
    if(Math.abs(origin - el.id) > 1) {
      el.parentElement.classList.toggle('panel-danger');    
    }
  };
  
  function dragover_handler(ev) {
   ev.preventDefault();
   // Set the dropEffect to move
   ev.dataTransfer.dropEffect = "move"
  };
  
  function dragenter_handler(ev, el) {
    ev.preventDefault();
    if(Math.abs(origin - el.id) === 1 && origin !== el.id) {
      el.parentElement.classList.toggle('panel-success');    
    }
    else if(Math.abs(origin - el.id) > 1) {
      el.parentElement.classList.toggle('panel-danger');    
    }
        
  }
  
  function dragleave_handler(ev, el) {
    ev.preventDefault();
    if(Math.abs(origin - el.id) === 1 && origin !== el.id) {
      el.parentElement.classList.toggle('panel-success');    
    }
    else if(Math.abs(origin - el.id) > 1) {
      el.parentElement.classList.toggle('panel-danger');    
    }
  }
  
  
  function updateTaskProgressState(taskId, destination) {
    xhr = new XMLHttpRequest();

    xhr.open('POST',
      encodeURI('task/' + taskId ));
    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    xhr.setRequestHeader('X-CSRF-Token', token);
    xhr.onload = function() {
        if (xhr.status !== 200) {
          alert('Request failed.  Returned status of ' + xhr.status);
        } 
        else{
        document.getElementById('task-'+ taskId).outerHTML = xhr.responseText;
        }
    };
    xhr.send(encodeURI('destination=' + destination));
  };
  
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<<h1>About</h1>
<p></p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% if logged_in? %>
  <div class="row">
      <% if @user.projects.any? %>
        <%= render "projects/project_list" %>
      <% else %>
      <h1>You don't have any projects yet,  <%= link_to " add a project", new_project_path, class: "primary" %></h1>
      <% end %>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to this thing!</h1>
    <h2>
      Organize stuff. For fun.
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="panel panel-default" draggable="true" ondragstart="dragstart_handler(event, <%= task[:progress_state]%>, <%=task.id%> );" id="task-<%=task.id%>">
  <div class="panel-heading">
    <h4 class="panel-title row"><span class="col-sm-10"><%= task.name %></span> 
      <span class="col-sm-2"><%= link_to "", task, method: :delete,
                      data: { confirm: "You sure?" }, 
                      class: "glyphicon glyphicon-trash pull-right" %></span>
    </h4>
  </div>
  <div class="panel-body">
    <%= task.description %>
      <% if current_user?(task.project.user) %>
  <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>